//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedule.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Classroom
    {
        public int Id { get; set; }

        [Required]
        [Display (Name="Название Аудитории")]
        public string Name { get; set; }
    
        public virtual Lesson Lesson { get; set; }
    }
}
