//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Group = new HashSet<Group>();
        }
    
        public int Id { get; set; }
        public int TeacherId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Group> Group { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
